# Generated by Django 4.2.2 on 2023-07-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_historial_total"),
    ]

    operations = [
        migrations.AddField(
            model_name="historial",
            name="total_con_descuento",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
