# Generated by Django 4.2.2 on 2023-07-11 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_historial_usuario"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historial",
            name="usuario",
        ),
    ]
