# Generated by Django 4.2.2 on 2023-07-11 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0008_remove_historial_usuario"),
    ]

    operations = [
        migrations.AddField(
            model_name="historial",
            name="usuario",
            field=models.ForeignKey(
                
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="historial",
            name="id_historial",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
