# Generated by Django 4.2.2 on 2023-07-11 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_alter_historial_usuario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historial",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.usuario"
            ),
        ),
    ]
